config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :events, except: ["index"] do
    resources :bookings, only: [:create, :update]
  end
  resources :bookings, only: [:destroy]
  resources :networks, except: [:new, :index]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  get '/dashboard', to: 'dashboards#dashboard'
  get '/profile', to: 'profiles#profile'
  post '/profile', to: 'profiles#update'
  get '/profile/:id', to: 'profiles#show', as: :profile_show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates :nb_guest, numericality: { greater_than: 0 }
  validate :check_event_capacity

  def check_event_capacity
    if self.nb_guest > self.event.calcul_capacity_book
      errors.add(:nb_guest, "Number of guests reached")
    end
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :chatrooms

  EXPERIENCE = ["Dinner", "Cooking Class", "Food Tour", "Brunch"]
  LANGUAGE = ["French", "English", "Spanish", "Portuguese"]

  validates :title, :experience, :address, :description, :date, :language, :capacity, presence: true
  validates :experience, inclusion: { in: EXPERIENCE }
  validates :language, inclusion: { in: LANGUAGE }

  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def show
    @user = current_user
  end

  def calcul_capacity_book
    capacity - bookings.where(confirmation: true).sum(&:nb_guest)
  end

  def calcul_capacity
    capacity - bookings.sum(&:nb_guest)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/network.rb
class Network < ApplicationRecord
  belongs_to :user
  has_many :networks_users
  has_many :networkers, through: :networks_user, source: :user
end

app/models/networks_user.rb
class NetworksUser < ApplicationRecord
  belongs_to :user
  belongs_to :network
  has_many :events, through: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  has_many :events
  has_many :networks
  has_many :bookings, through: :events
  has_one_attached :photo
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def home
    @users = User.all
  end

  def edit

  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.event = @event
    if @event.bookings.count >= @event.capacity
      render 'events/show', status: :unprocessable_entity
    elsif @booking.save
      redirect_to event_path(@event), notice: "You made a reservation for #{@booking.nb_guest} people"
    elsif render 'events/show', status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.confirmation = true
    @event = Event.find(params[:event_id])
    if @event.calcul_capacity_book >= @booking.nb_guest
      @booking.update(confirmation: true)
    else
      render 'dashboard', status: :unprocessable_entity
    end
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to dashboard_path
    else
      render 'dashboard', status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:nb_guest, :id, :confirmation, :event_id, :user_id)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def dashboard
    @event = current_user.events
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit]
  skip_before_action :authenticate_user!, only: [ :show ]

  def index
    if params[:address].present?
      sql_query = <<~SQL
        events.address ILIKE :query
      SQL
      @events = Event.where(sql_query, query: "%#{params[:address]}%")
    else
      @events = Event.all
    end

    @booking = Booking.new
    @event = Event.all
  end

  def show
    @booking = Booking.new
    @event = Event.find(params[:id])
    @markers = [
      {
        lat: @event.latitude,
        lng: @event.longitude
      }
    ]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_create)
    @event.user = current_user
    if @event.save
      redirect_to profile_path
    else
      render 'events/new', status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to profile_path
  end

  private

  def params_create
    params.require(:event).permit(:title, :experience, :address, :description, :date, :language, :capacity, :user_id, :query)
  end

  def event_params
    params.require(:events).permit(:id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom, {
        html: render_to_string(partial: "message", locals: {message: @message}),
        user_id: current_user.id
        }
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController

  def show
  @network = Network.find(params[:id])
  @networks_user = NetworksUser.all.reject { |network_user| network_user.user == current_user}
  @user = User.all
  @events = Event.all
  @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @events = Event.all
    @booking = Booking.new
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit]

  def profile
    @user = current_user
    @event = current_user.events
  end

  def show
    @event = @user.events
  end

  def edit
  end

  def update

    if current_user.update(params_create)

      redirect_to profile_path
    else

      render profile_path, status: :unprocessable_entity
    end
  end

  private

  def set_profile
    @user = User.find(params[:id])
  end

  def params_create
    params.require('/profile').permit(:id, :email, :nickname, :avatar, :address, :bio, :photo )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>" data-chatroom-subscription-user-id-value="<%= current_user.id %>">
  <h1>#<%= @chatroom.name %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
          <%= render "messages/message", message: message %>
      <% end %>
    </div>
</div>
<%= simple_form_for [@chatroom, @message], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f| %>
  <%= f.input :content,
    label: false,
    placeholder: "Message ##{@chatroom.name}",
    wrapper_html: {class: "flex-grow-1"} %>
  <%= f.submit "Send", id: 'send', class: "btn btn-primary mb-3" %>
<% end %>

app/views/dashboards/dashboard.html.erb
<h1>Dashboard</h1>
<ul>
  <% @event.each do |e| %>
        <li><%= e.title %> :
          <% e.bookings.each do |b| %>
            <% if b.confirmation.nil? %>
              <%= b.confirmation %>
              <%= link_to "link", event_booking_path(e, b), data: { turbo_method: "patch" } %>
              <%= b.nb_guest %>
            <% end %>
          <% end %>
        </li>
    <% end %>
</ul>

<%= render 'shared/new_event' %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="form-login">

        <h1>Edit Event</h1>

        <%= simple_form_for @event do |f| %>
            <%= f.input :title,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "title" } %>
            <%= f.input :experience, collection: Event::EXPERIENCE,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "experience" } %>
            <%= f.input :address,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "address" }%>
            <%= f.input :description,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "description" }%>
            <%= f.input :date,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "date" }%>
            <%= f.input :language, collection: Event::LANGUAGE,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "language" }%>
            <%= f.input :capacity,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "capacity" }%>
            <%= f.button :submit, "Edit Event" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<script type = "text/javascript">


if (window.location.pathname == '/events/new') {

  console.log("Hello")

  let input = document.getElementById("event_title");
  let navBar = document.getElementById("nav-d-none");

  input.addEventListener("focus", () => {
    document.getElementById("nav-d-none").classList.add("d-none");
  });

  var currentTab = 0;
  document.addEventListener("turbo:load", function(event) {
    showTab(currentTab);
  });

  function showTab(n) {

    var x = document.getElementsByClassName("tab");
    x[n].style.display = "block";

    if (n == 0) {
    document.getElementById("prevBtn").style.display = "none";
    } else {
    document.getElementById("prevBtn").style.display = "inline";
    }
    if (n == (x.length + 1)) {
    document.getElementById("nextBtn").innerHTML = '<i class="fa fa-angle-double-right"></i>';
    } else {
    document.getElementById("nextBtn").innerHTML = '<i class="fa fa-angle-double-right"></i>';
    }
    fixStepIndicator(n)
  }

  function nextPrev(n) {
    var x = document.getElementsByClassName("tab");

    if (n == 1 && !validateForm()) return false;

    x[currentTab].style.display = "none";
    currentTab = currentTab + n;

    if (currentTab >= (x.length)) {

    document.getElementById("nextprevious").style.display = "none";
    document.getElementById("all-steps").style.display = "none";
    document.getElementById("register").style.display = "none";
    document.getElementById("text-message").style.display = "block";

    // document.getElementById("nextBtn").classList.add("d-none");
    // document.getElementById("lastBtn").classList.remove("d-none");
    }
    showTab(currentTab);
  }

  function validateForm() {
    var x, y, i, valid = true;
    x = document.getElementsByClassName("tab");
    y = x[currentTab].getElementsByTagName("input");
    for (i = 0; i < y.length; i++) {
      if (y[i].value == "") {
          y[i].className += " invalid";
          valid = false;
      }
    }
    if (valid) {
      document.getElementsByClassName("step")[currentTab].className += " finish";
    }
    return valid;
  }

  function fixStepIndicator(n) {
    var i, x = document.getElementsByClassName("step");
    for (i = 0; i < x.length; i++) {
      x[i].className = x[i].className.replace(" active", "");
    }
    x[n].className += " active";
  }

  // global.nextPrev = nextPrev

};

</script>


<div class="container" id="show">
    <div class="row d-flex justify-content-center align-items-center" style="margin-top: 168px;">
        <div class="col-md-8">
                <h1 id="register">Feel like sharing a meal ?</h1>
                <div class="all-steps" id="all-steps">
                  <span class="step"><i class="fa-solid fa-bowl-food"></i></span>
                  <span class="step"><i class="fa-solid fa-comment"></i></span>
                  <span class="step"><i class="fa-solid fa-calendar-day"></i></span>
                  <span class="step"><i class="fa-solid fa-location-dot"></i></span>
                  <span class="step"><i class="fa-solid fa-language"></i></span>
                </div>

            <%= simple_form_for @event, html: { id: "regForm" } do |f|  %>
                <div class="tab start" id="focus-d-none">
                  <h6>Choose a name and a type for your meal</h6>
                    <p>
                      <%= f.input :title,
                        required: false,
                        autofocus: true,
                        label: false,
                        input_html: { autocomplete: "title" } %>
                    </p>
                    <p>
                      <%= f.input :experience, collection: Event::EXPERIENCE,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "type" } %>
                    </p>
                </div>
                <div class="tab">
                    <h6>What are you proposing ? (description to be seen by users)</h6>
                    <p>
                      <%= f.input :description,
                        required: true,
                        autofocus: true,
                        label: false,
                        input_html: { autocomplete: "description" } %>
                    </p>
                </div>
                <div class="tab">
                    <h6>What day do we come and how much can we do?</h6>
                    <p>
                      <%= f.input :date, as: :date, html5: true %>
                    </p>
                    <p>
                      <%= f.input :capacity,
                        required: true,
                        autofocus: true,
                        label: false,
                        input_html: { autocomplete: "capacity" } %>
                    </p>
                </div>
                <div class="tab">
                    <h6>Where to go?</h6>
                    <p>
                      <%= f.input :address,
                      required: true,
                      autofocus: true,
                      label: false,
                      input_html: {data: {address_autocomplete_target: "address"}},
                      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
                    </p>
                </div>
                <div class="tab">
                    <h6>What language will you speak ?</h6>
                    <p>
                      <%= f.input :language, collection: Event::LANGUAGE,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "language" } %>
                    </p>
                </div>
                <div class="thanks-message text-center" id="text-message"> <%= image_tag 'logo.png', class: 'mb-4', style: 'width: 100' %>
                    <h3>Your meal is online!</h3>
                    <button type="submit" id=""><i class="fa-solid fa-check"></i></button>
                </div>
                <div style="overflow:auto;" id="nextprevious">
                    <div style="float:right;">
                      <button type="button" id="prevBtn" onclick="nextPrev(-1)"><i class="fa fa-angle-double-left"></i></button>
                      <button type="button" id="nextBtn" onclick="nextPrev(1)"><i class="fa fa-angle-double-right"></i></button>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/events/show.html.erb
<%= render 'shared/banner_map' %>
<div class="container-fluid my-4">
    <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
      <div class="col" id="col-top-map">
        <h2 class="text-center my-3"><%= @event.title.capitalize %></h2>
        <p><%= @event.description %></p>
        <p><%= @event.date.strftime("%m/%d/%Y at %I:%M%p") %></p>
        <p><strong>Slots</strong> : <%= @event.calcul_capacity_book %>/<%= @event.capacity %></p>
        <% if @event.calcul_capacity_book > 0 %>
          <%= simple_form_for [@event, @booking] do |f| %>
            <%= f.input :nb_guest,
                          required: true,
                          autofocus: false,
                          label: 'For how many people?',
                          input_html: { autocomplete: "Guest", min: 0, max: @event.capacity } %>
            <%= f.button :submit, "Reserved", class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food-Breaker</title>
    <link rel="icon" type="image/png" href="https://img.icons8.com/nolan/344/pokeball.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body style="background: linear-gradient(270deg, #f1fffe, #f8eeff);">

    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

  </body>
</html>

app/views/messages/_message.html.erb
  <div class="skin-msg msg-info-<%= message.user == current_user ? 'sender' : 'receiver' %>" id="message-<%= message.id %>">
    <small>
      <%= cl_image_tag message.user.photo.key, widht: 30, height: 30, id: 'avatar-msg', class: 'avatar' %>
      <strong> <%= message.user.nickname %></strong>
      <small><i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i></small>
    </small>
    <p><%= message.content %></p>
  </div>

app/views/networks/edit.html.erb
<h1>Coucou Edit Network </h1>

app/views/networks/show.html.erb
<div id='div-logo'>
  <%= image_tag 'logo.png', height: 120, id: 'logo' %>
  <h1 class="text-center"><%= @network.name.split(" ").first %></h1> <h1 id='h' class="text-center"><%= @network.name.split(" ").last %></h1>
</div>

<div class="container" id="event-head">
  <h2>My friends</h2>
  <hr>
</div>

  <div class="container" style="display: flex; justify-content: center; margin-top: 12px;">
    <% @network.networks_users.map(&:user).each do |n| %>
      <%= link_to profile_show_path(n) do %>
        <%= cl_image_tag n.photo.key, class: 'avatar-profile', crop: :thumb, gravity: :face %>
      <% end %>
    <% end %>
</div>

<div class="container" id="event-head">
  <h2>My friends' events</h2>
  <hr>
</div>

<div class="product">
  <ul>
    <% @networks_user.each do |network_user| %>
      <% network_user.events.each do |event| %>
        <%= link_to event_path(event) do %>
          <li>
            <div class="card-product">
              <% if event.photos.attached? %>
                <%= cl_image_tag event.user.photo.key,
                                                  height: 170,
                                                  width: 150,
                                                  class: "card-img-top",
                                                  style: "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))" %>
              <% else %>
                <img src="https://source.unsplash.com/random?profile?food" style="height: 170, width: 150" class="card-img-top"/>
              <% end %>
            </div>
            <div class="card-product-infos">
              <h2><%= event.title %></h2>
            </div>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div id='div-logo'>
  <%= image_tag 'logo.png', height: 120, id: 'logo' %>
  <h1 class="text-center">Food </h1> <h1 id='h' class="text-center">Breaker</h1>
</div>
<%= render 'shared/head' %>
<%= render 'shared/card_events' %>
<%= render 'shared/new_event' %>

app/views/profiles/profile.html.erb
<%= render 'shared/banner_profiles' %>
<%= render 'shared/new_event' %>

app/views/profiles/show.html.erb
<%= render 'shared/banner_profile' %>

<div class="container ratting">
  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star-half-stroke"></i>
</div>

<div class="container bio" id="event-head">
  <h2>Bio of <%= @user.nickname.capitalize %></h2>
  <hr>
  <p><%= @user.bio %></p>
</div>
<div class="container bio" id="event-head">
  <h2>His events</h2>
  <hr>
</div>
  <%= render 'shared/card_product' %>

app/views/shared/_banner_map.html.erb
<div class="banner-profil">
  <div style="width: 100%; height: 200px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <%= link_to profile_show_path(@event.user) do %>
    <%= cl_image_tag @event.user.photo.key, width: 100, height: 100, crop: :thumb, gravity: :face, class: 'avatar-large' %>
  <% end %>
</div>

app/views/shared/_banner_profile.html.erb
<div class="banner-profile">
  <div style="width: 100%; height: 200px;">
  <%# if @user.photo.attached? %>
    <%#= cl_image_tag @user.photo.key,
                                      height: 180,
                                      style: "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))" %>
  <%# else %>
    <img src="https://source.unsplash.com/random?food" style="height: 180px; width: 100%" class="card-img-top"/>
  <%# end %>
  </div>
</div>
<div class="avatar-profile">
  <%= cl_image_tag @user.photo.key, width: 100, height: 100, crop: :thumb, gravity: :face, class: 'avatar-large' %>
</div>

app/views/shared/_card_events.html.erb
<main id="home-card">
  <% @events.each do |e| %>
    <%= link_to event_path(e) do %>
      <div class="container-fluid mt-1" id='event-home'>
        <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
          <div class="col">
            <div class="card-sl ">
              <li>
                <%# <img src="https://source.unsplash.com/random?food" alt=""> %>
                <% if e.photos.attached? %>
                  <%= cl_image_tag e.user.photo.key,
                                                    height: 170,
                                                    width: 150,
                                                    class: "card-img-top",
                                                    style: "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))" %>
                <% else %>
                  <img src="https://source.unsplash.com/random?food" style="height: 170px; width: 100%" class="card-img-top"/>
                <% end %>
                  <div class="card-heading">
                      <h4><%= e.title.capitalize %></h4>
                      <p class="card-text"><%= e.description.truncate(40) %></p>
                      <p class="card-slot">Slots : <%= e.calcul_capacity_book %>/<%= e.capacity %></p>
                </div>
              </li>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_card_product.html.erb
<div class="product">
  <ul>
    <% @event.each do |e| %>
      <%= link_to event_path(e) do %>
        <li>
          <div class="card-product">
            <% if e.photos.attached? %>
              <%= cl_image_tag e.user.photo.key,
                                                height: 170,
                                                width: 150,
                                                class: "card-img-top",
                                                style: "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))" %>
            <% else %>
              <img src="https://source.unsplash.com/random?profile?food" style="height: 170, width: 150" class="card-img-top"/>
            <% end %>
          </div>
          <div class="card-product-infos">
            <h2><%= e.title %></h2>
            <%= link_to 'X', event_path(e), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, id: 'Oo'%>
            <% e.bookings.each do |b| %>
              <% if b.confirmation.nil? %>
                <%= b.confirmation %>
                <div class="slot">
                  <p>Guest: <%= b.nb_guest %></p>
                  <div class="btn-card">
                    <%= link_to "Decline", booking_path(b), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-secondary' %>
                    <%= link_to "Accept", event_booking_path(e, b), data: { turbo_method: "patch" }, class: 'btn btn-primary' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 d-none" data-controller="sweetalert" data-sweetalert-text-value="<%= notice %>" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 d-none" data-controller="sweetalert" data-sweetalert-text-value="<%= alert %>" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_head.html.erb
<div class="container" id="event-head">
  <h2>Discover the meals near you</h2>
  <hr>
</div>

app/views/shared/_navbar.html.erb
<div class="fixed-bottom" id="nav-d-none">
  <ul class="navbar-fab">
    <% if user_signed_in? %>
      <li>
        <%= link_to root_path do %>
          <%= image_tag 'home.png', width: 40, height: 40 %>
        <% end %>
      </li>

      <li >
        <%= link_to chatroom_path(Chatroom.first, anchor: "message-#{Chatroom.first.messages.last&.id}"), data: {turbo: false} do %>
          <%= image_tag 'dashboard.png', width: 40, height: 40 %>
        <% end %>
      </li>

      <li>
        <%= link_to network_path(current_user.networks.first) do %>
          <%= image_tag 'commu.png', width: 40, height: 40 %>
        <% end %>
      </li>

      <li >
        <%= link_to profile_path do %>
          <%= image_tag 'profile.png', width: 40, height: 40 %>
        <% end %>
      </li>

      </li>
    <% else %>
      <li>
        <%= link_to root_path do %>
          <%= image_tag 'home.png', width: 40, height: 40 %>
        <% end %>
      </li>

      <li >
        <%= link_to user_session_path do %>
          <%= image_tag 'dashboard.png', width: 40, height: 40, class: 'disabled' %>
        <% end %>
      </li>

      <li>
        <%= link_to user_session_path do %>
          <%= image_tag 'commu.png', width: 40, height: 40, class: 'disabled' %>
        <% end %>
      </li>
      <li>
        <%= link_to user_session_path do %>
          <%= image_tag 'on.png', width: 40, height: 40 %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_new_event.html.erb
<div class="btn-pluss-contain">
  <%= link_to new_event_path, class: 'btn-pluss' do %>
  <%= image_tag 'add.png', width: 60, height: 60  %>
  <% end %>
</div>